### ISSUE TITLE
Prompt when transferring funds：Method not found

### ISSUE THREAD

**Issue by roway168** [skynetcap/solanaj#42]
org.p2p.solanaj.rpc.RpcException: Method not found
	at org.p2p.solanaj.rpc.RpcClient.call(RpcClient.java:101)
	at org.p2p.solanaj.rpc.RpcApi.getRecentBlockhash(RpcApi.java:61)
	at org.p2p.solanaj.rpc.RpcApi.getRecentBlockhash(RpcApi.java:51)
	at org.p2p.solanaj.rpc.RpcApi.sendTransaction(RpcApi.java:87)
	at org.p2p.solanaj.rpc.RpcApi.sendTransaction(RpcApi.java:115)
	at org.p2p.solanaj.rpc.RpcApi.sendTransaction(RpcApi.java:70)
	at org.p2p.solanaj.token.TokenManager.transferCheckedToSolAddress(TokenManager.java:95)

**Comment by skynetcap** [comment]
[getRecentBlockhash RPC Method](https://solana.com/docs/rpc/deprecated/getrecentblockhash)

Returns a recent block hash from the ledger, and a fee schedule that can be used to compute the cost of submitting a transaction using it.

**Deprecated Method**
This method is expected to be removed in solana-core v2.0. Please use [getLatestBlockhash](https://solana.com/docs/rpc/http/getlatestblockhash) instead.
