### ISSUE TITLE
method getAccountInfo() for encoding jsonParsed error

### ISSUE THREAD

**Issue by jkllx** [skynetcap/solanaj#77]
`
 Map<String, Object> params = new HashMap<>();
            params.put("encoding", "jsonParsed");
            AccountInfo accountInfo = rpcClient.getApi().getAccountInfo(new PublicKey(tableAccountAddress), params);
`

use getAccountInfo to get lookup table account info,get error 
`
com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.result.value.data

	at com.squareup.moshi.JsonUtf8Reader.beginArray(JsonUtf8Reader.java:144)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:79)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at org.p2p.solanaj.rpc.RpcClient.call(RpcClient.java:162)
	at org.p2p.solanaj.rpc.RpcApi.getAccountInfo(RpcApi.java:307)
`

**Comment by cwf404** [comment]
https://solana.com/zh/docs/rpc#parsed-responses
